# Generated by Django 3.2.12 on 2022-02-09 10:45

import TutorService.core.utils.json_serializer
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('type', models.CharField(choices=[('ACCOUNT_CREATED', 'account_created'), ('PASSWORD_RESET_LINK_SENT', 'password_reset_link_sent'), ('PASSWORD_RESET', 'password_reset'), ('PASSWORD_CHANGED', 'password_changed'), ('PLACED_OFFER', 'placed_offer'), ('EDITED_OFFER', 'edited_offer'), ('CANCELLED_OFFER', 'cancelled_offer'), ('APPLIED_OFFER', 'applied_offer'), ('SETTLED_NEW_PRICE', 'settled_new_price'), ('CANCELLED_APPLY', 'cancelled_apply'), ('FROZEN_MONEY', 'frozen_money'), ('NOT_ENOUGH_MONEY', 'not_enough_money'), ('CANCELLED_PAYMENT', 'cancelled_payment'), ('PAYMENT_DONE', 'payment_done')], max_length=255)),
                ('parameters', models.JSONField(blank=True, default=dict, encoder=TutorService.core.utils.json_serializer.CustomJsonEncoder)),
                ('offer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='offer.offer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('date',),
            },
        ),
    ]
