# Generated by Django 3.2.12 on 2022-02-09 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('image', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='offer-image')),
                ('price', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('start_lesson', models.DateTimeField()),
                ('status', models.CharField(choices=[('IN_SEARCH', 'in_search'), ('PAID', 'paid'), ('CANCELLED', 'cancelled')], max_length=255)),
                ('subject', models.CharField(choices=[('MATHEMATICS', 'mathematics'), ('CHEMISTRY', 'chemistry'), ('PHYSICS', 'physics'), ('BIOLOGY', 'biology')], max_length=255)),
                ('grade', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11')], max_length=255)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_offers', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_offers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
